name: "svg/*.svg Builder"

on:
  push:
    branches:
      - master

jobs:
  main:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: "npm install"
      - run: "node ./generator.js"
      - run: "rm .gitignore"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./svg
